# Scoring Configuration - How to rank evidence cards

# Default scoring formula weights (can be overridden per agency)
default_weights:
  specificity: 0.35  # How specific to the agency/program
  compliance: 0.35   # Regulatory/mandate pressure
  budget: 0.3        # Budget/procurement signals

# Specificity scoring (1-3 scale)
specificity_indicators:
  score_3:  # Highest - Direct agency/bureau mention
    - "agency name mentioned"
    - "bureau name mentioned"
    - "specific program or system"
    - "OIG report about agency"
    - "GAO report about agency"
  score_2:  # Medium - Domain-specific
    - "industry-specific term"
    - "specialized technology"
    - "NIST guidance"
    - "sector-specific"
  score_1:  # Low - General guidance
    - "general cybersecurity"
    - "best practices"
    - "framework guidance"

# Compliance scoring (1-3 scale)
compliance_indicators:
  score_3:  # Highest - Hard mandates
    - "SHALL"
    - "MUST"
    - "REQUIRED"
    - "OMB M-"
    - "Executive Order"
    - "statutory requirement"
  score_2:  # Medium - Strong guidance
    - "SHOULD"
    - "RECOMMENDED"
    - "GAO recommendation"
    - "OIG finding"
  score_1:  # Low - Optional guidance
    - "MAY"
    - "COULD"
    - "best practice"
    - "consideration"

# Budget scoring (0-3 scale)
budget_indicators:
  score_3:  # Highest - Specific amounts
    - "$X million"
    - "$X billion"
    - "contract value"
    - "IDIQ ceiling"
  score_2:  # Medium - Procurement activity
    - "procurement"
    - "acquisition"
    - "contract"
    - "task order"
    - "RFP"
  score_1:  # Low - General budget mention
    - "funding"
    - "budget"
    - "resources"
    - "investment"
  score_0:  # None - No budget signal

# Bonus scoring
bonuses:
  recency_boost: 0.5  # If document date <= 24 months
  csf_diversity: 0.3  # If helps balance CSF functions
  
# Tie-breaker rules (in order)
tie_breakers:
  1: "Prefer more recent documents"
  2: "Prefer shorter quotes"
  3: "Prefer earlier page numbers"
  4: "Prefer alphabetical by source"
